# Generated by go2rpm 1
%bcond_without check

# https://github.com/kljensen/snowball
%global goipath         github.com/kljensen/snowball
Version:                0.6.0

%gometa

%global common_description %{expand:
Go implementation of the Snowball stemmers.}

%global golicenses      LICENSE
%global godocs          HISTORY.md README.md english/README.md\\\
                        norwegian/README.md russian/README.md\\\
                        spanish/README.md swedish/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go implementation of the Snowball stemmers

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in gostem; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc HISTORY.md README.md english/README.md norwegian/README.md
%doc russian/README.md spanish/README.md swedish/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Sun Jan 26 03:58:48 CET 2020 Marcel Metz <mmetz@adrian-broher.net> - 0.6.0-1
- Initial package
